import turtle
turtle.setup(800,600)
window=turtle.Screen()
window.title("YELLOWWWW")
window.bgcolor("yellow")
the_turtle=turtle.getturtle()
the_turtle.hideturtle()
the_turtle.forward(100)
the_turtle.left(90)
the_turtle.forward(100)
the_turtle.left(90)
the_turtle.forward(100)
the_turtle.left(90)
the_turtle.forward(100)
